# Generated by Django 4.0.3 on 2022-04-12 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_page_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
