# Generated by Django 4.0.3 on 2022-04-12 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pages_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
